/**
 * Copyright (C) 2010 Sopra (support_movalys@sopra.com)
 *
 * This file is part of Movalys MDK.
 * Movalys MDK is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * Movalys MDK is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 * You should have received a copy of the GNU Lesser General Public License
 * along with Movalys MDK. If not, see <http://www.gnu.org/licenses/>.
 */



// /MFUI/control/button
FOUNDATION_EXPORT NSInteger const TAG_MFBUTTON_BUTTON;

// /MFUI/control/date
FOUNDATION_EXPORT NSInteger const TAG_MFDATEPICKER_DATEBUTTON;
FOUNDATION_EXPORT NSInteger const TAG_MFDATEPICKER_DATEPICKER;
FOUNDATION_EXPORT NSInteger const TAG_MFDATEPICKER_CONFIRMBUTTON;
FOUNDATION_EXPORT NSInteger const TAG_MFDATEPICKER_CANCELBUTTON;

// /MFUI/control/image
FOUNDATION_EXPORT NSInteger const TAG_MFENUMIMAGE_IMAGEVIEW;
FOUNDATION_EXPORT NSInteger const TAG_MFENUMIMAGE_IMAGE;

// /MFUI/control/label
FOUNDATION_EXPORT NSInteger const TAG_MFLABEL_LABEL;

// /MFUI/control/list
FOUNDATION_EXPORT NSInteger const TAG_MFFIXEDLIST_TABLEVIEW;
FOUNDATION_EXPORT NSInteger const TAG_MFFIXEDLIST_TOPBARVIEW;

FOUNDATION_EXPORT NSInteger const TAG_MFPICKERLIST_PICKERVIEW;
FOUNDATION_EXPORT NSInteger const TAG_MFPICKERLIST_CONFIRMBUTTON;
FOUNDATION_EXPORT NSInteger const TAG_MFPICKERLIST_CANCELBUTTON;

FOUNDATION_EXPORT NSInteger const TAG_MFSIMPLEPICKERLIST_PICKERBUTTON;
FOUNDATION_EXPORT NSInteger const TAG_MFSIMPLEPICKERLIST_PICKERVIEW;
FOUNDATION_EXPORT NSInteger const TAG_MFSIMPLEPICKERLIST_CONFIRMBUTTON;
FOUNDATION_EXPORT NSInteger const TAG_MFSIMPLEPICKERLIST_CANCELBUTTON;

// /MFUI/control/number
FOUNDATION_EXPORT NSInteger const TAG_MFNUMBERPICKER_PICKERVIEW;
FOUNDATION_EXPORT NSInteger const TAG_MFNUMBERPICKER_NUMBERBUTTON;
FOUNDATION_EXPORT NSInteger const TAG_MFNUMBERPICKER_CONFIRMBUTTON;
FOUNDATION_EXPORT NSInteger const TAG_MFNUMBERPICKER_CANCELBUTTON;

// /MFUI/control/photo
FOUNDATION_EXPORT NSInteger const TAG_MFPHOTOTHUMBNAIL_PHOTOVIEW;
FOUNDATION_EXPORT NSInteger const TAG_MFPHOTOTHUMBNAIL_DATE;
FOUNDATION_EXPORT NSInteger const TAG_MFPHOTOTHUMBNAIL_TITRE;
FOUNDATION_EXPORT NSInteger const TAG_MFPHOTOTHUMBNAIL_DESCRIPTION;

// /MFUI/control/position
FOUNDATION_EXPORT NSInteger const TAG_MFPOSITION_LATITUDE;
FOUNDATION_EXPORT NSInteger const TAG_MFPOSITION_LONGITUDE;
FOUNDATION_EXPORT NSInteger const TAG_MFPOSITION_GPSBUTTON;
FOUNDATION_EXPORT NSInteger const TAG_MFPOSITION_MAPBUTTON;

// /MFUI/control/processing

// /MFUI/control/signature
FOUNDATION_EXPORT NSInteger const TAG_MFSIGNATURE_SIGNATURE;
FOUNDATION_EXPORT NSInteger const TAG_MFSIGNATURE_CONFIRMBUTTON;
FOUNDATION_EXPORT NSInteger const TAG_MFSIGNATURE_CANCELBUTTON;
FOUNDATION_EXPORT NSInteger const TAG_MFSIGNATURE_CLEARBUTTON;

// /MFUI/control/slider
FOUNDATION_EXPORT NSInteger const TAG_MFSLIDER_SLIDER;
FOUNDATION_EXPORT NSInteger const TAG_MFSLIDER_SLIDERVALUE;

// /MFUI/control/switch
FOUNDATION_EXPORT NSInteger const TAG_MFSWITCH_SWITCHCOMPONENT;

// /MFUI/control/textfield
FOUNDATION_EXPORT NSInteger const TAG_MFBROWSEURLTEXTFIELD_TEXTFIELD;
FOUNDATION_EXPORT NSInteger const TAG_MFBROWSEURLTEXTFIELD_ACTIONBUTTON;

FOUNDATION_EXPORT NSInteger const TAG_MFCALLPHONENUMBERTEXTFIELD_TEXTFIELD;
FOUNDATION_EXPORT NSInteger const TAG_MFCALLPHONENUMBERTEXTFIELD_ACTIONBUTTON;

FOUNDATION_EXPORT NSInteger const TAG_MFDOUBLETEXTFIELD_TEXTFIELD;
FOUNDATION_EXPORT NSInteger const TAG_MFDOUBLETEXTFIELD_ACTIONBUTTON;

FOUNDATION_EXPORT NSInteger const TAG_MFINTEGERTEXTFIELD_TEXTFIELD;
FOUNDATION_EXPORT NSInteger const TAG_MFINTEGERTEXTFIELD_ACTIONBUTTON;

FOUNDATION_EXPORT NSInteger const TAG_MFREGULAREXPRESSIONTEXTFIELD_TEXTFIELD;
FOUNDATION_EXPORT NSInteger const TAG_MFREGULAREXPRESSIONTEXTFIELD_ACTIONBUTTON;

FOUNDATION_EXPORT NSInteger const TAG_MFSENDEMAILTEXTFIELD_TEXTFIELD;
FOUNDATION_EXPORT NSInteger const TAG_MFSENDEMAILTEXTFIELD_ACTIONBUTTON;

FOUNDATION_EXPORT NSInteger const TAG_MFTEXTFIELD_TEXTFIELD;

FOUNDATION_EXPORT NSInteger const TAG_MFTEXTVIEW_TEXTVIEW;

// /MFUI/control/tooltip

// /MFUI/control/webview
FOUNDATION_EXPORT NSInteger const TAG_MFWEBVIEW_WEBVIEW;
FOUNDATION_EXPORT NSInteger const TAG_MFWEBVIEW_SPINNER;
